### ISSUE TITLE
Unable to open any type of terminal in iPadOS/iOS

### ISSUE THREAD

**Issue by claudeLovelace** [polyipseity/obsidian-terminal#35] opened 2023-12-31 12:22 UTC
I’ve been trying all the options stated in the readme.md to open a terminal but I don’t see an option that would allow me to open a terminal.

**Comment by polyipseity** [comment] 2024-01-03 03:18
On mobile platforms, you can only open the developer terminal. How does opening the developer terminal fails? Could you describe it in more details.

**Comment by claudeLovelace** [comment] 2024-01-09 03:14
Nothing opens. I am unable to find or use any type of terminal on my iPad when using the Obsidian plugin.

**Comment by polyipseity** [comment] 2024-01-11 02:01
Can you send me your settings? You should see a textbox containing the settings as JSON after clicking on the below button:

![image](https://github.com/polyipseity/obsidian-terminal/assets/17660922/a394683f-edab-42f4-9b68-6b3f963f43fe)

**Comment by claudeLovelace** [comment] 2024-01-13 10:57
I am unable to obtain a JSON file of my settings from the Obsidian app on my iPadOS. So instead, I recorded a video of me going through all the settings. Hope this helps!

<iframe src="https://drive.google.com/file/d/1nXPq5jvjRiESzm9wJuY7Usoe2ZWxAepA/>
</iframe>

**Comment by polyipseity** [comment] 2024-01-13 13:18
> I am unable to obtain a JSON file of my settings from the Obsidian app on my iPadOS. So instead, I recorded a video of me going through all the settings. Hope this helps!
> 
> https://drive.google.com/file/d/1nXPq5jvjRiESzm9wJuY7Usoe2ZWxAepA/
> 
> Edit: embedding isn't working so I added the full link above.

It looks like the plugin is not loading at all. Yet it also doesn't produce an error that makes Obsidian disable the plugin. Would uninstalling the plugin completely and reinstalling it work?

**Comment by claudeLovelace** [comment] 2024-01-13 22:07
Yeah, that's what I tried first but it still didn't change.

**Comment by polyipseity** [comment] 2024-06-06 12:16
Sorry for not updating... Any news?

**Comment by polyipseity** [comment] 2024-06-23 11:22
Actually, I highly suspect this is caused by the same reason as in https://github.com/polyipseity/obsidian-show-hidden-files/issues/5, which is caused by a library detecting iPadOS as other platforms wrongly. If so, this should be fixed.

**Closed by polyipseity** 2024-06-23 11:22 UTC
Labels: bug, question
